{% set name = "diffhalos" %}
{% set version = "0.1.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ArgonneCPAC/diffhalos/archive/v{{ version }}.tar.gz
  sha256: b9d306ececc6889aa6888edda610d2ec420ee6e7a8dec26798a1e49eda02780e

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  noarch: python

requirements:
  host:
    - python =={{ python_min }}
    - setuptools >=45
    - setuptools-scm >=7
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - jax
    - diffmah
    - dsps
    - flowjax

test:
  imports:
    - diffhalos
  commands:
    - pip check
  requires:
    - pip
    - python =={{ python_min }}

about:
  summary: Library for differentiable generation of halo lightcones
  home: https://github.com/ArgonneCPAC/diffhalos
  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - beckermr
